chore: edit ci setting

diff --git a/.github/workflows/an-ci.yml b/.github/workflows/an-ci.yml
--- a/.github/workflows/an-ci.yml
+++ b/.github/workflows/an-ci.yml
@@ -90,6 +90,9 @@ jobs:
       - name: Grant execute permission for Gradle
         run: chmod +x ./gradlew
 
+      - name: Verify Gradle Cache Integrity
+        run: ls -lah ~/.gradle || echo "Gradle cache not found."
+
       - name: Verify Gradle Wrapper Version
         run: ./gradlew --version 8.10.2
 
